table ABC
	lineageTag: 6a84c040-84ee-4de6-9104-38455827ad12

	measure Orderline =
			
			VAR SalesByProduct =
			    CALCULATETABLE (
			        ADDCOLUMNS (
			            SUMMARIZE ( 'Fact Material Movement', 'Fact Material Movement'[MaterialMovement_ProductId] ),
			            "@ProdSales", [Material Movement Turnover Count]
			        ),
			        ALLSELECTED ( 'Fact Material Movement' )
			    )
			VAR AllSales =
			    CALCULATE (
			        [Material Movement Turnover Count],
			        ALLSELECTED ( 'Fact Material Movement' )
			    )
			VAR CumulatedPctByProduct =
			    ADDCOLUMNS (
			        SalesByProduct,
			        "@CumulatedPct",
			        VAR CurrentSalesAmt = [@ProdSales]
			        VAR CumulatedSales =
			            FILTER (
			                SalesByProduct,
			                [@ProdSales] >= CurrentSalesAmt
			            )
			        VAR CumulatedSalesAmount =
			            SUMX (
			                CumulatedSales,
			                [@ProdSales]
			            )
			        VAR Perc =
			            DIVIDE (
			                CumulatedSalesAmount,
			                AllSales
			            )
			        RETURN
			            Perc
			    )
			VAR ProductsInClass =
			    FILTER (
			        CROSSJOIN (
			            CumulatedPctByProduct,
			            'ABC'
			        ),
			        AND (
			            [@CumulatedPct] > 'ABC'[ABCFrom],
			            [@CumulatedPct] <= 'ABC'[ABCTo]
			        )
			    )
			VAR Result =
			    CALCULATE (             -- The pattern is the same for every measure, just
			        [Material Movement Turnover Count],     -- change this measure reference for other measures
			        KEEPFILTERS ( ProductsInClass )
			    )
			RETURN
			    Result
		formatString: #,0
		lineageTag: 4db7f335-8cad-4590-b8fe-fba6c6542be1

	measure Products =
			
			VAR SalesByProduct =
			    CALCULATETABLE (
			        ADDCOLUMNS (
			            SUMMARIZE ( 'Fact Material Movement', 'Fact Material Movement'[MaterialMovement_ProductId] ),
			            "@ProdSales", [Material Movement Turnover Count]
			        ),
			        ALLSELECTED ( 'Fact Material Movement' )
			    )
			VAR AllSales =
			    CALCULATE (
			        [Material Movement Turnover Count],
			        ALLSELECTED ( 'Fact Material Movement' )
			    )
			VAR CumulatedPctByProduct =
			    ADDCOLUMNS (
			        SalesByProduct,
			        "@CumulatedPct",
			        VAR CurrentSalesAmt = [@ProdSales]
			        VAR CumulatedSales =
			            FILTER (
			                SalesByProduct,
			                [@ProdSales] >= CurrentSalesAmt
			            )
			        VAR CumulatedSalesAmount =
			            SUMX (
			                CumulatedSales,
			                [@ProdSales]
			            )
			        VAR Perc =
			            DIVIDE (
			                CumulatedSalesAmount,
			                AllSales
			            )
			        RETURN
			            Perc
			    )
			VAR ProductsInClass =
			    FILTER (
			        CROSSJOIN (
			            CumulatedPctByProduct,
			            'ABC'
			        ),
			        AND (
			            [@CumulatedPct] > 'ABC'[ABCFrom],
			            [@CumulatedPct] <= 'ABC'[ABCTo]
			        )
			    )
			VAR Result =
			    CALCULATE (             -- The pattern is the same for every measure, just
			        [Material Movement Product Count],     -- change this measure reference for other measures
			        KEEPFILTERS ( ProductsInClass )
			    )
			RETURN
			    Result
		formatString: #,0
		lineageTag: 0fe777db-64bf-4bf4-a690-ccd363bc5fd5

	measure Units =
			
			VAR SalesByProduct =
			    CALCULATETABLE (
			        ADDCOLUMNS (
			            SUMMARIZE ( 'Fact Material Movement', 'Fact Material Movement'[MaterialMovement_ProductId] ),
			            "@ProdSales", [Material Movement Turnover Count]
			        ),
			        ALLSELECTED ( 'Fact Material Movement' )
			    )
			VAR AllSales =
			    CALCULATE (
			        [Material Movement Turnover Count],
			        ALLSELECTED ( 'Fact Material Movement' )
			    )
			VAR CumulatedPctByProduct =
			    ADDCOLUMNS (
			        SalesByProduct,
			        "@CumulatedPct",
			        VAR CurrentSalesAmt = [@ProdSales]
			        VAR CumulatedSales =
			            FILTER (
			                SalesByProduct,
			                [@ProdSales] >= CurrentSalesAmt
			            )
			        VAR CumulatedSalesAmount =
			            SUMX (
			                CumulatedSales,
			                [@ProdSales]
			            )
			        VAR Perc =
			            DIVIDE (
			                CumulatedSalesAmount,
			                AllSales
			            )
			        RETURN
			            Perc
			    )
			VAR ProductsInClass =
			    FILTER (
			        CROSSJOIN (
			            CumulatedPctByProduct,
			            'ABC'
			        ),
			        AND (
			            [@CumulatedPct] > 'ABC'[ABCFrom],
			            [@CumulatedPct] <= 'ABC'[ABCTo]
			        )
			    )
			VAR Result =
			    CALCULATE (             -- The pattern is the same for every measure, just
			        [Material Movement Turnover Units],     -- change this measure reference for other measures
			        KEEPFILTERS ( ProductsInClass )
			    )
			RETURN
			    Result
		formatString: #,0
		lineageTag: b1c3abfa-c4ee-44c5-83c5-daf9098d0b18

	measure 'ICO Palletes' =
			
			VAR SalesByProduct =
			    CALCULATETABLE (
			        ADDCOLUMNS (
			            SUMMARIZE ( 'Fact Material Movement', 'Fact Material Movement'[MaterialMovement_SupplierId] ),
			            "@ProdSales", [Material Movement Turnover Palletes]
			        ),
			        ALLSELECTED ( 'Fact Material Movement' )
			    )
			VAR AllSales =
			    CALCULATE (
			        [Material Movement Turnover Palletes],
			        ALLSELECTED ( 'Fact Material Movement' )
			    )
			VAR CumulatedPctByProduct =
			    ADDCOLUMNS (
			        SalesByProduct,
			        "@CumulatedPct",
			        VAR CurrentSalesAmt = [@ProdSales]
			        VAR CumulatedSales =
			            FILTER (
			                SalesByProduct,
			                [@ProdSales] >= CurrentSalesAmt
			            )
			        VAR CumulatedSalesAmount =
			            SUMX (
			                CumulatedSales,
			                [@ProdSales]
			            )
			        VAR Perc =
			            DIVIDE (
			                CumulatedSalesAmount,
			                AllSales
			            )
			        RETURN
			            Perc
			    )
			VAR ProductsInClass =
			    FILTER (
			        CROSSJOIN (
			            CumulatedPctByProduct,
			            'ABC'
			        ),
			        AND (
			            [@CumulatedPct] > 'ABC'[ABCFrom],
			            [@CumulatedPct] <= 'ABC'[ABCTo]
			        )
			    )
			VAR Result =
			    CALCULATE (             -- The pattern is the same for every measure, just
			        [Material Movement Supplier Count],     -- change this measure reference for other measures
			        KEEPFILTERS ( ProductsInClass )
			    )
			RETURN
			    Result
		lineageTag: fe540614-8d4e-4d71-97f9-6deab2c45ab9

	measure 'ICO Units' =
			
			VAR SalesByProduct =
			    CALCULATETABLE (
			        ADDCOLUMNS (
			            SUMMARIZE ( 'Fact Material Movement', 'Fact Material Movement'[MaterialMovement_SupplierId] ),
			            "@ProdSales", [Material Movement Turnover Units]
			        ),
			        ALLSELECTED ( 'Fact Material Movement' )
			    )
			VAR AllSales =
			    CALCULATE (
			        [Material Movement Turnover Units],
			        ALLSELECTED ( 'Fact Material Movement' )
			    )
			VAR CumulatedPctByProduct =
			    ADDCOLUMNS (
			        SalesByProduct,
			        "@CumulatedPct",
			        VAR CurrentSalesAmt = [@ProdSales]
			        VAR CumulatedSales =
			            FILTER (
			                SalesByProduct,
			                [@ProdSales] >= CurrentSalesAmt
			            )
			        VAR CumulatedSalesAmount =
			            SUMX (
			                CumulatedSales,
			                [@ProdSales]
			            )
			        VAR Perc =
			            DIVIDE (
			                CumulatedSalesAmount,
			                AllSales
			            )
			        RETURN
			            Perc
			    )
			VAR ProductsInClass =
			    FILTER (
			        CROSSJOIN (
			            CumulatedPctByProduct,
			            'ABC'
			        ),
			        AND (
			            [@CumulatedPct] > 'ABC'[ABCFrom],
			            [@CumulatedPct] <= 'ABC'[ABCTo]
			        )
			    )
			VAR Result =
			    CALCULATE (             -- The pattern is the same for every measure, just
			        [Material Movement Supplier Count],     -- change this measure reference for other measures
			        KEEPFILTERS ( ProductsInClass )
			    )
			RETURN
			    Result
		formatString: 0
		lineageTag: 808e03e4-52f7-46db-b099-34673c842787

	measure 'ICO Orderline' =
			
			VAR SalesByProduct =
			    CALCULATETABLE (
			        ADDCOLUMNS (
			            SUMMARIZE ( 'Fact Material Movement', 'Fact Material Movement'[MaterialMovement_SupplierId] ),
			            "@ProdSales", [Material Movement Turnover Count]
			        ),
			        ALLSELECTED ( 'Fact Material Movement' )
			    )
			VAR AllSales =
			    CALCULATE (
			        [Material Movement Turnover Count],
			        ALLSELECTED ( 'Fact Material Movement' )
			    )
			VAR CumulatedPctByProduct =
			    ADDCOLUMNS (
			        SalesByProduct,
			        "@CumulatedPct",
			        VAR CurrentSalesAmt = [@ProdSales]
			        VAR CumulatedSales =
			            FILTER (
			                SalesByProduct,
			                [@ProdSales] >= CurrentSalesAmt
			            )
			        VAR CumulatedSalesAmount =
			            SUMX (
			                CumulatedSales,
			                [@ProdSales]
			            )
			        VAR Perc =
			            DIVIDE (
			                CumulatedSalesAmount,
			                AllSales
			            )
			        RETURN
			            Perc
			    )
			VAR ProductsInClass =
			    FILTER (
			        CROSSJOIN (
			            CumulatedPctByProduct,
			            'ABC'
			        ),
			        AND (
			            [@CumulatedPct] > 'ABC'[ABCFrom],
			            [@CumulatedPct] <= 'ABC'[ABCTo]
			        )
			    )
			VAR Result =
			    CALCULATE (             -- The pattern is the same for every measure, just
			        [Material Movement Supplier Count],     -- change this measure reference for other measures
			        KEEPFILTERS ( ProductsInClass )
			    )
			RETURN
			    Result
		formatString: 0
		lineageTag: 07e975ef-1245-4690-993b-ca0f814ae44e

	measure 'Product Suppliers classified by Palletes' = ```
			
			VAR SalesByProductSupplier = 
			    CALCULATETABLE (
			        ADDCOLUMNS (
			            SUMMARIZE (
			                'Fact Material Movement',
			                'Product'[ProductSupplier]
			            ),
			            "@ProdSales",
			                [Material Movement Turnover Palletes]
			        ),
			        ALLSELECTED ( 'Fact Material Movement' )
			    )
			
			VAR AllSales =
			    CALCULATE (
			        [Material Movement Turnover Palletes],
			        ALLSELECTED ( 'Fact Material Movement' )
			    )
			
			VAR CumulatedPctByProduct =
			    ADDCOLUMNS (
			        SalesByProductSupplier,
			        "@CumulatedPct",
			        VAR CurrentSalesAmt = [@ProdSales]
			        VAR CumulatedSales =
			            FILTER (
			                SalesByProductSupplier,
			                [@ProdSales] >= CurrentSalesAmt
			            )
			        RETURN
			            DIVIDE (
			                SUMX ( CumulatedSales, [@ProdSales] ),
			                AllSales
			            )
			    )
			
			VAR ABCFrom =
			    SELECTEDVALUE ( 'ABC'[ABCFrom] )
			
			VAR ABCTo =
			    SELECTEDVALUE ( 'ABC'[ABCTo] )
			
			VAR IsABCInContext =
			    NOT ISBLANK ( ABCFrom )
			
			VAR ProductsInClass =
			    FILTER (
			        CumulatedPctByProduct,
			        [@CumulatedPct] > ABCFrom
			            && [@CumulatedPct] <= ABCTo
			    )
			
			RETURN
			IF (
			    IsABCInContext,
			    /* === ABC řádek === */
			    CALCULATE (
			        [Material Movement Product Supplier Count],
			        KEEPFILTERS ( ProductsInClass )
			    ),
			    /* === Total (bez ABC v kontextu) === */
			    CALCULATE (
			        [Material Movement Product Supplier Count],
			        ALL ( 'ABC' )
			    )
			)
			
			```
		lineageTag: c92ed1cb-5ff6-4e55-9cc4-1153c7be8ef6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Orderlines classified by Palletes' = ```
			
			VAR SalesByProductSupplier = 
			    CALCULATETABLE (
			        ADDCOLUMNS (
			            SUMMARIZE (
			                'Fact Material Movement',
			                'Product'[ProductSupplier]
			            ),
			            "@ProdSales",
			                [Material Movement Turnover Palletes]
			        ),
			        ALLSELECTED ( 'Fact Material Movement' )
			    )
			
			VAR AllSales =
			    CALCULATE (
			        [Material Movement Turnover Palletes],
			        ALLSELECTED ( 'Fact Material Movement' )
			    )
			
			VAR CumulatedPctByProduct =
			    ADDCOLUMNS (
			        SalesByProductSupplier,
			        "@CumulatedPct",
			        VAR CurrentSalesAmt = [@ProdSales]
			        VAR CumulatedSales =
			            FILTER (
			                SalesByProductSupplier,
			                [@ProdSales] >= CurrentSalesAmt
			            )
			        RETURN
			            DIVIDE (
			                SUMX ( CumulatedSales, [@ProdSales] ),
			                AllSales
			            )
			    )
			
			VAR ABCFrom =
			    SELECTEDVALUE ( 'ABC'[ABCFrom] )
			
			VAR ABCTo =
			    SELECTEDVALUE ( 'ABC'[ABCTo] )
			
			VAR IsABCInContext =
			    NOT ISBLANK ( ABCFrom )
			
			VAR ProductsInClass =
			    FILTER (
			        CumulatedPctByProduct,
			        [@CumulatedPct] > ABCFrom
			            && [@CumulatedPct] <= ABCTo
			    )
			
			RETURN
			IF (
			    IsABCInContext,
			    /* === ABC řádek === */
			    CALCULATE (
			        [Material Movement Turnover Count],
			        KEEPFILTERS ( ProductsInClass )
			    ),
			    /* === Total (bez ABC v kontextu) === */
			    CALCULATE (
			        [Material Movement Turnover Count],
			        ALL ( 'ABC' )
			    )
			)
			
			```
		formatString: #,0
		lineageTag: 6eede6ed-8533-48dc-8dae-aae0c225b967

	measure 'Units classified by Palletes' = ```
			
			VAR SalesByProductSupplier = 
			    CALCULATETABLE (
			        ADDCOLUMNS (
			            SUMMARIZE (
			                'Fact Material Movement',
			                'Product'[ProductSupplier]
			            ),
			            "@ProdSales",
			                [Material Movement Turnover Palletes]
			        ),
			        ALLSELECTED ( 'Fact Material Movement' )
			    )
			
			VAR AllSales =
			    CALCULATE (
			        [Material Movement Turnover Palletes],
			        ALLSELECTED ( 'Fact Material Movement' )
			    )
			
			VAR CumulatedPctByProduct =
			    ADDCOLUMNS (
			        SalesByProductSupplier,
			        "@CumulatedPct",
			        VAR CurrentSalesAmt = [@ProdSales]
			        VAR CumulatedSales =
			            FILTER (
			                SalesByProductSupplier,
			                [@ProdSales] >= CurrentSalesAmt
			            )
			        RETURN
			            DIVIDE (
			                SUMX ( CumulatedSales, [@ProdSales] ),
			                AllSales
			            )
			    )
			
			VAR ABCFrom =
			    SELECTEDVALUE ( 'ABC'[ABCFrom] )
			
			VAR ABCTo =
			    SELECTEDVALUE ( 'ABC'[ABCTo] )
			
			VAR IsABCInContext =
			    NOT ISBLANK ( ABCFrom )
			
			VAR ProductsInClass =
			    FILTER (
			        CumulatedPctByProduct,
			        [@CumulatedPct] > ABCFrom
			            && [@CumulatedPct] <= ABCTo
			    )
			
			RETURN
			IF (
			    IsABCInContext,
			    /* === ABC řádek === */
			    CALCULATE (
			        [Material Movement Turnover Units],
			        KEEPFILTERS ( ProductsInClass )
			    ),
			    /* === Total (bez ABC v kontextu) === */
			    CALCULATE (
			        [Material Movement Turnover Units],
			        ALL ( 'ABC' )
			    )
			)
			
			```
		lineageTag: 0e754e9b-bb62-4761-8b67-685824cfd1bf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Products classified by Orderlines' = ```
			
			VAR SalesByProductSupplier = 
			    CALCULATETABLE (
			        ADDCOLUMNS (
			            SUMMARIZE (
			                'Fact Material Movement',
			                [MaterialMovement_ProductId]
			            ),
			            "@ProdSales",
			                [Material Movement Turnover Count]
			        ),
			        ALLSELECTED ( 'Fact Material Movement' )
			    )
			
			VAR AllSales =
			    CALCULATE (
			        [Material Movement Turnover Count],
			        ALLSELECTED ( 'Fact Material Movement' )
			    )
			
			VAR CumulatedPctByProduct =
			    ADDCOLUMNS (
			        SalesByProductSupplier,
			        "@CumulatedPct",
			        VAR CurrentSalesAmt = [@ProdSales]
			        VAR CumulatedSales =
			            FILTER (
			                SalesByProductSupplier,
			                [@ProdSales] >= CurrentSalesAmt
			            )
			        RETURN
			            DIVIDE (
			                SUMX ( CumulatedSales, [@ProdSales] ),
			                AllSales
			            )
			    )
			
			VAR ABCFrom =
			    SELECTEDVALUE ( 'ABC'[ABCFrom] )
			
			VAR ABCTo =
			    SELECTEDVALUE ( 'ABC'[ABCTo] )
			
			VAR IsABCInContext =
			    NOT ISBLANK ( ABCFrom )
			
			VAR ProductsInClass =
			    FILTER (
			        CumulatedPctByProduct,
			        [@CumulatedPct] > ABCFrom
			            && [@CumulatedPct] <= ABCTo
			    )
			
			RETURN
			IF (
			    IsABCInContext,
			    /* === ABC řádek === */
			    CALCULATE (
			        [Material Movement Product Count],
			        KEEPFILTERS ( ProductsInClass )
			    ),
			    /* === Total (bez ABC v kontextu) === */
			    CALCULATE (
			        [Material Movement Product Count],
			        ALL ( 'ABC' )
			    )
			)
			
			```
		formatString: #,0
		lineageTag: a3047397-6c16-4c33-b4fd-7db2a25720f9

	measure 'Orderlines classified by Orderlines' = ```
			
			VAR SalesByProductSupplier = 
			    CALCULATETABLE (
			        ADDCOLUMNS (
			            SUMMARIZE (
			                'Fact Material Movement',
			                [MaterialMovement_ProductId]
			            ),
			            "@ProdSales",
			                [Material Movement Turnover Count]
			        ),
			        ALLSELECTED ( 'Fact Material Movement' )
			    )
			
			VAR AllSales =
			    CALCULATE (
			        [Material Movement Turnover Count],
			        ALLSELECTED ( 'Fact Material Movement' )
			    )
			
			VAR CumulatedPctByProduct =
			    ADDCOLUMNS (
			        SalesByProductSupplier,
			        "@CumulatedPct",
			        VAR CurrentSalesAmt = [@ProdSales]
			        VAR CumulatedSales =
			            FILTER (
			                SalesByProductSupplier,
			                [@ProdSales] >= CurrentSalesAmt
			            )
			        RETURN
			            DIVIDE (
			                SUMX ( CumulatedSales, [@ProdSales] ),
			                AllSales
			            )
			    )
			
			VAR ABCFrom =
			    SELECTEDVALUE ( 'ABC'[ABCFrom] )
			
			VAR ABCTo =
			    SELECTEDVALUE ( 'ABC'[ABCTo] )
			
			VAR IsABCInContext =
			    NOT ISBLANK ( ABCFrom )
			
			VAR ProductsInClass =
			    FILTER (
			        CumulatedPctByProduct,
			        [@CumulatedPct] > ABCFrom
			            && [@CumulatedPct] <= ABCTo
			    )
			
			RETURN
			IF (
			    IsABCInContext,
			    /* === ABC řádek === */
			    CALCULATE (
			        [Material Movement Turnover Count],
			        KEEPFILTERS ( ProductsInClass )
			    ),
			    /* === Total (bez ABC v kontextu) === */
			    CALCULATE (
			        [Material Movement Turnover Count],
			        ALL ( 'ABC' )
			    )
			)
			
			```
		formatString: #,0
		lineageTag: bc9451e9-5f01-4181-be91-b9c847bdbf9b

	measure 'Units classified by Orderlines' = ```
			
			VAR SalesByProductSupplier = 
			    CALCULATETABLE (
			        ADDCOLUMNS (
			            SUMMARIZE (
			                'Fact Material Movement',
			                [MaterialMovement_ProductId]
			            ),
			            "@ProdSales",
			                [Material Movement Turnover Count]
			        ),
			        ALLSELECTED ( 'Fact Material Movement' )
			    )
			
			VAR AllSales =
			    CALCULATE (
			        [Material Movement Turnover Count],
			        ALLSELECTED ( 'Fact Material Movement' )
			    )
			
			VAR CumulatedPctByProduct =
			    ADDCOLUMNS (
			        SalesByProductSupplier,
			        "@CumulatedPct",
			        VAR CurrentSalesAmt = [@ProdSales]
			        VAR CumulatedSales =
			            FILTER (
			                SalesByProductSupplier,
			                [@ProdSales] >= CurrentSalesAmt
			            )
			        RETURN
			            DIVIDE (
			                SUMX ( CumulatedSales, [@ProdSales] ),
			                AllSales
			            )
			    )
			
			VAR ABCFrom =
			    SELECTEDVALUE ( 'ABC'[ABCFrom] )
			
			VAR ABCTo =
			    SELECTEDVALUE ( 'ABC'[ABCTo] )
			
			VAR IsABCInContext =
			    NOT ISBLANK ( ABCFrom )
			
			VAR ProductsInClass =
			    FILTER (
			        CumulatedPctByProduct,
			        [@CumulatedPct] > ABCFrom
			            && [@CumulatedPct] <= ABCTo
			    )
			
			RETURN
			IF (
			    IsABCInContext,
			    /* === ABC řádek === */
			    CALCULATE (
			        [Material Movement Turnover Units],
			        KEEPFILTERS ( ProductsInClass )
			    ),
			    /* === Total (bez ABC v kontextu) === */
			    CALCULATE (
			        [Material Movement Turnover Units],
			        ALL ( 'ABC' )
			    )
			)
			
			```
		formatString: #,0
		lineageTag: 34bca02e-02c7-46db-87b0-aed8dca73f01

	column ABCId
		dataType: int64
		formatString: 0
		lineageTag: c07b97ab-c19b-4eb7-baeb-9dc0612f33a4
		summarizeBy: count
		sourceColumn: ABCId

		annotation SummarizationSetBy = Automatic

	column ABCName
		dataType: string
		lineageTag: d4f3b3fc-3826-4d26-ac10-dc3ca372a200
		summarizeBy: none
		sourceColumn: ABCName

		annotation SummarizationSetBy = Automatic

	column ABCFrom
		dataType: double
		lineageTag: 52c8a020-1e2c-416a-987b-923e8e79f0a5
		summarizeBy: sum
		sourceColumn: ABCFrom

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ABCTo
		dataType: double
		lineageTag: 99bb5ce1-b5a1-4dcd-a289-c50237321ca0
		summarizeBy: sum
		sourceColumn: ABCTo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition ABC = m
		mode: import
		source =
				let
				    Source = Sql.Database("BORGERS.LOCAL", "JIP_DWH"),
				    adm_ABC = Source{[Schema="adm",Item="ABC"]}[Data]
				in
				    adm_ABC

