table Date
	lineageTag: 71fb670f-0951-4cfe-8244-194600b96e51

	column DateId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ee0f1391-9bd3-4425-a7fd-5314469d86f9
		summarizeBy: none
		sourceColumn: DateId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DateDate
		dataType: dateTime
		formatString: General Date
		lineageTag: da139d52-e796-4077-b1b8-6b055e19ad7f
		summarizeBy: none
		sourceColumn: DateDate

		variation Variation
			isDefault
			relationship: 3eba4621-8df7-41e7-87e9-93150d8259a1
			defaultHierarchy: LocalDateTable_1177f4db-4251-4842-aa66-5a04eafae0ce.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column DateCalendarYear
		dataType: int64
		formatString: 0
		lineageTag: f5cca422-759c-40eb-9f70-9e1af3f0a154
		summarizeBy: sum
		sourceColumn: DateCalendarYear

		annotation SummarizationSetBy = Automatic

	column DateCalendarYearWeekName
		dataType: string
		lineageTag: e5a5705d-7ed0-42c6-995a-5fee1310a6f0
		summarizeBy: none
		sourceColumn: DateCalendarYearWeekName

		annotation SummarizationSetBy = Automatic

	column DateCalendarYearMonthName
		dataType: string
		lineageTag: dd66804f-4f25-447e-b20a-fc6fba22e632
		summarizeBy: none
		sourceColumn: DateCalendarYearMonthName

		annotation SummarizationSetBy = Automatic

	column DateMonthNumberOfYear
		dataType: int64
		formatString: 0
		lineageTag: 549462fd-613f-4669-ae04-43e047e3201c
		summarizeBy: sum
		sourceColumn: DateMonthNumberOfYear

		annotation SummarizationSetBy = Automatic

	column 'Date Czech Day Name Of Week'
		dataType: string
		lineageTag: f690fd1a-8883-4b21-a7ce-f74c338b8506
		summarizeBy: none
		sourceColumn: Date Czech Day Name Of Week
		sortByColumn: DateDayNumberOfWeek

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column DateDayNumberOfWeek
		dataType: int64
		formatString: 0
		lineageTag: 16e29f37-a514-41e2-ba77-f6b92113a9dd
		summarizeBy: sum
		sourceColumn: DateDayNumberOfWeek

		annotation SummarizationSetBy = Automatic

	column DateCzechMonthName
		dataType: string
		lineageTag: 30f1825b-064f-4e4b-80c8-a72334fae110
		summarizeBy: none
		sourceColumn: DateCzechMonthName
		sortByColumn: DateMonthNumberOfYear

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: deec4388-e9f9-4b8d-a428-c670797dac82

		level DateDate
			lineageTag: 969c89d3-1dc8-4f15-99cc-e3ee8e4bd0d6
			column: DateDate

		level DateCalendarYear
			lineageTag: 8b537b0a-0c9e-4cd0-b937-93a7bcc4ada5
			column: DateCalendarYear

		level DateCzechMonthName
			lineageTag: 08d1eb2c-efd7-4fdb-a2e7-af1b39f3a8fa
			column: DateCzechMonthName

	partition Date = m
		mode: import
		source =
				let
				    Source = Sql.Database("BORGERS.LOCAL", "JIP_DWH"),
				    dbo_v_DimDate = Source{[Schema="dbo",Item="v_DimDate"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(dbo_v_DimDate,{{"DateCzechDayNameOfWeek", "Date Czech Day Name Of Week"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

