table Document
	lineageTag: bfe0cede-d0f7-46e1-9ab3-33939fe58cc9

	measure 'Document Count' = COUNTROWS()
		formatString: 0
		lineageTag: cbe5c9a5-dc04-40f1-9788-bb0d777e2d71

	column DocumentId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2c54eba6-fcf9-4cd5-bdfd-1efc56853888
		summarizeBy: none
		sourceColumn: DocumentId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DocumentNumber
		dataType: string
		lineageTag: a0dd1ac0-a11f-480c-a5f7-3f2a80934526
		summarizeBy: none
		sourceColumn: DocumentNumber

		annotation SummarizationSetBy = Automatic

	partition Document = m
		mode: import
		source =
				let
				    Source = Sql.Database("BORGERS.LOCAL", "JIP_DWH"),
				    dbo_DimDocument = Source{[Schema="dbo",Item="v_DimDocument"]}[Data]
				in
				    dbo_DimDocument

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

