table 'Fact Material Movement'
	lineageTag: eb949167-dcbd-47a6-bebd-6aa2de690348

	measure 'Material Movement Turnover Count' = COUNTROWS()
		formatString: #,0
		lineageTag: 9049d144-1fda-424c-8c54-7a014797b139

	measure 'Material Movement Internal Count' =
			CALCULATE(
			    COUNTROWS(),
			    Supplier[Supplier Is JIP]
			)
		formatString: #,0
		lineageTag: fdf22aec-26b8-4a7e-8640-ba91029fb5a9

	measure 'Material Movement External Count' =
			CALCULATE(
			    COUNTROWS(),
			    NOT( Supplier[Supplier Is JIP])
			)
		formatString: #,0
		lineageTag: de617168-c517-406a-8465-423c4632d1b9

	measure 'Material Movement External Palletes' =
			CALCULATE(
			    SUM('Fact Material Movement'[MaterialMovementTurnoverPalletes]),
			    NOT( Supplier[Supplier Is JIP])
			)
		formatString: #,0.00
		lineageTag: 75d83dd6-1f28-490f-abd6-6119214229a6

	measure 'Material Movement Internall Palletes' = ```
			CALCULATE(
			    SUM('Fact Material Movement'[MaterialMovementTurnoverPalletes]),
			     Supplier[Supplier Is JIP]
			)
			
			```
		formatString: #,0.00
		lineageTag: 2ebe5ba5-2f0e-4a8b-b992-b2d320fd516b

	measure 'Material Movement External Palletes %' = [Material Movement External Palletes] / SUM([MaterialMovementTurnoverPalletes])
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 785bd327-0429-4f92-b68c-0d2d6fc9f529

	measure 'Material Movement Document Count' = DISTINCTCOUNT('Fact Material Movement'[MaterialMovement_DocumentId])
		formatString: 0
		lineageTag: 53c2819a-14d2-44cd-b4e2-c29b29b8b013

	measure 'Material Movement Turnover Palletes' = SUM('Fact Material Movement'[MaterialMovementTurnoverPalletes])
		lineageTag: 4b2bd784-4438-4fec-8682-2b643fa746d0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Material Movement Turnover Units' = SUM('Fact Material Movement'[MaterialMovementTurnoverUnits])
		lineageTag: 051d5dea-4370-4a5f-bccb-c8a578d7887d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Material Movement Day Count' = DISTINCTCOUNT('Fact Material Movement'[MaterialMovement_DateId])
		formatString: 0
		lineageTag: 453fc21c-50da-4553-9665-736da836451c

	measure 'Material Movement Product Count' = DISTINCTCOUNT('Fact Material Movement'[MaterialMovement_ProductId])
		formatString: 0
		lineageTag: 29896474-33dd-4319-a225-bba382704edc

	measure 'Material Movement Turnover Full Palletes' = SUM('Fact Material Movement'[MaterialMovementTurnoverFullPalletes])
		formatString: #,0
		lineageTag: 398ee66c-5e8e-4ef6-ac65-099b64d82fb2

	measure 'Material Movement Supplier Count' = DISTINCTCOUNT('Fact Material Movement'[MaterialMovement_SupplierId])
		formatString: 0
		lineageTag: 3580e7dc-0630-4b15-b0bd-d4c7b059f07e

	column MaterialMovement_DateId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ca0cca8c-bd76-4722-aa48-9851004a5a61
		summarizeBy: none
		sourceColumn: MaterialMovement_DateId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MaterialMovement_BranchId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 94e014a7-83d4-4f28-b163-e8021f4bb201
		summarizeBy: none
		sourceColumn: MaterialMovement_BranchId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MaterialMovement_DocumentId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 008e1d1a-8298-4f05-911b-ce4cd98e0867
		summarizeBy: none
		sourceColumn: MaterialMovement_DocumentId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MaterialMovement_ProductId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1209ac3f-2e04-4081-a046-6ad8dda295a2
		summarizeBy: none
		sourceColumn: MaterialMovement_ProductId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MaterialMovement_SupplierId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2499cd1d-77ed-43fb-bc56-0c28fe3bce56
		summarizeBy: none
		sourceColumn: MaterialMovement_SupplierId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MaterialMovementTurnoverUnits
		dataType: double
		isHidden
		lineageTag: 939747b7-7e67-417d-b657-6c6feedf055b
		summarizeBy: sum
		sourceColumn: MaterialMovementTurnoverUnits

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MaterialMovementTurnoverPalletes
		dataType: double
		isHidden
		lineageTag: 8618dd3e-7b1a-43d4-a54d-4d59b177ecff
		summarizeBy: sum
		sourceColumn: MaterialMovementTurnoverPalletes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MaterialMovement_MovementTypeId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6f64d5a7-2adb-4ccb-9bd5-dfd0fca2cddc
		summarizeBy: none
		sourceColumn: MaterialMovement_MovementTypeId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MaterialMovementTurnoverFullPalletes
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 54b8a22d-a7ae-4dc5-af78-fe4fef6ea05e
		summarizeBy: sum
		sourceColumn: MaterialMovementTurnoverFullPalletes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Fact Material Movement' = m
		mode: import
		source =
				let
				    Source = Sql.Database("BORGERS.LOCAL", "JIP_DWH"),
				    dbo_FactMaterialMovement = Source{[Schema="dbo",Item="v_FactMaterialMovement"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(dbo_FactMaterialMovement,{{"MaterialMovementTurnoverPalletes", "MaterialMovementTurnoverPalletes"}, {"MaterialMovementTurnoverUoM", "MaterialMovementTurnoverUnits"}})
				in
				    #"Renamed Columns"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

