table Supplier
	lineageTag: c4ac5f4e-ac57-40d0-abb6-a83a2bee7a94

	column SupplierId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3c11c621-01a6-4914-8fdf-b1f3b1eba9e3
		summarizeBy: none
		sourceColumn: SupplierId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SupplierICO
		dataType: string
		lineageTag: 0b8d7768-5f61-45fe-abba-6303fbe1f063
		summarizeBy: none
		sourceColumn: SupplierICO

		annotation SummarizationSetBy = Automatic

	column 'Supplier Is JIP'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1b8a9b09-c04e-4bc2-bf98-1546f0da1999
		summarizeBy: none
		sourceColumn: Supplier Is JIP

		annotation SummarizationSetBy = Automatic

	column 'Supplier Is JIP CZ' = IF(Supplier[Supplier Is JIP], "Ano", "Ne")
		lineageTag: 7b68d1c4-39cb-4fcd-b6a2-d2f8f050cd1c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column SupplierName
		dataType: string
		lineageTag: 4aa73f18-af4f-4537-a0c6-70928520cb4d
		summarizeBy: none
		sourceColumn: SupplierName

		annotation SummarizationSetBy = Automatic

	column SupplierCity
		dataType: string
		lineageTag: acca645c-bb8f-4c55-a430-92519897fc86
		summarizeBy: none
		sourceColumn: SupplierCity

		annotation SummarizationSetBy = Automatic

	column SupplierFullName
		dataType: string
		lineageTag: 3119b480-6cb4-45bd-8875-7e657958fcce
		summarizeBy: none
		sourceColumn: SupplierFullName

		annotation SummarizationSetBy = Automatic

	partition Supplier = m
		mode: import
		source =
				let
				    Source = Sql.Database("BORGERS.LOCAL", "JIP_DWH"),
				    dbo_DimSupplier = Source{[Schema="dbo",Item="v_DimSupplier"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(dbo_DimSupplier,{{"SupplierIsJIP", "Supplier Is JIP"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

