{
  "name": "JIP_PowerBI",
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "cs-CZ",
    "tables": [
      {
        "name": "Date",
        "lineageTag": "71fb670f-0951-4cfe-8244-194600b96e51",
        "columns": [
          {
            "name": "DateId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DateId",
            "formatString": "0",
            "lineageTag": "ee0f1391-9bd3-4425-a7fd-5314469d86f9",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateDate",
            "dataType": "dateTime",
            "sourceColumn": "DateDate",
            "formatString": "General Date",
            "lineageTag": "da139d52-e796-4077-b1b8-6b055e19ad7f",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "3eba4621-8df7-41e7-87e9-93150d8259a1",
                "defaultHierarchy": {
                  "table": "LocalDateTable_1177f4db-4251-4842-aa66-5a04eafae0ce",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateCalendarYear",
            "dataType": "int64",
            "sourceColumn": "DateCalendarYear",
            "formatString": "0",
            "lineageTag": "f5cca422-759c-40eb-9f70-9e1af3f0a154",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateCalendarYearWeekName",
            "dataType": "string",
            "sourceColumn": "DateCalendarYearWeekName",
            "lineageTag": "e5a5705d-7ed0-42c6-995a-5fee1310a6f0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateCalendarYearMonthName",
            "dataType": "string",
            "sourceColumn": "DateCalendarYearMonthName",
            "lineageTag": "dd66804f-4f25-447e-b20a-fc6fba22e632",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateMonthNumberOfYear",
            "dataType": "int64",
            "sourceColumn": "DateMonthNumberOfYear",
            "formatString": "0",
            "lineageTag": "549462fd-613f-4669-ae04-43e047e3201c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Date Czech Day Name Of Week",
            "dataType": "string",
            "sourceColumn": "Date Czech Day Name Of Week",
            "sortByColumn": "DateDayNumberOfWeek",
            "lineageTag": "f690fd1a-8883-4b21-a7ce-f74c338b8506",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateDayNumberOfWeek",
            "dataType": "int64",
            "sourceColumn": "DateDayNumberOfWeek",
            "formatString": "0",
            "lineageTag": "16e29f37-a514-41e2-ba77-f6b92113a9dd",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateCzechMonthName",
            "dataType": "string",
            "sourceColumn": "DateCzechMonthName",
            "sortByColumn": "DateMonthNumberOfYear",
            "lineageTag": "30f1825b-064f-4e4b-80c8-a72334fae110",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"BORGERS.LOCAL\", \"JIP_DWH\"),",
                "    dbo_v_DimDate = Source{[Schema=\"dbo\",Item=\"v_DimDate\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(dbo_v_DimDate,{{\"DateCzechDayNameOfWeek\", \"Date Czech Day Name Of Week\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "deec4388-e9f9-4b8d-a428-c670797dac82",
            "levels": [
              {
                "name": "DateDate",
                "ordinal": 0,
                "column": "DateDate",
                "lineageTag": "969c89d3-1dc8-4f15-99cc-e3ee8e4bd0d6"
              },
              {
                "name": "DateCalendarYear",
                "ordinal": 1,
                "column": "DateCalendarYear",
                "lineageTag": "8b537b0a-0c9e-4cd0-b937-93a7bcc4ada5"
              },
              {
                "name": "DateCzechMonthName",
                "ordinal": 2,
                "column": "DateCzechMonthName",
                "lineageTag": "08d1eb2c-efd7-4fdb-a2e7-af1b39f3a8fa"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DateTableTemplate_6d33a379-3767-46fc-a494-f05ce9fe588a",
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "bcf93555-c5a5-4118-a02c-acf21215e54b",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "formatString": "General Date",
            "lineageTag": "40056517-2312-4ff4-b65c-4e37f0ae06b6",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "formatString": "0",
            "lineageTag": "38c0e129-efb0-42e4-95d4-32c5b8dbe397",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "formatString": "0",
            "lineageTag": "4ddf5f62-d537-430b-875e-0dc22987729d",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "e4e053d0-26c2-4815-9dd4-2f891784cb6c",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "lineageTag": "88b6ae35-c1ce-43c6-bddb-ff581cd8d635",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "d81586c5-13fb-4cd5-a905-5c8e38003447",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "formatString": "0",
            "lineageTag": "c4f35709-1a6e-4461-a606-237a04f66217",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DateTableTemplate_6d33a379-3767-46fc-a494-f05ce9fe588a",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "c0de4420-f14d-44bb-9f5b-62fab8fc8a32",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "70599a59-276b-451f-9ad5-20ec0ab7e7aa"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "3e0dcb95-f833-4114-affd-48949f586de5"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "301017db-46d2-4704-8fae-4db09747abaa"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "5e498094-df07-4ba7-9bb8-13a2dfee4c7b"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ]
      },
      {
        "name": "LocalDateTable_1177f4db-4251-4842-aa66-5a04eafae0ce",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "7e006a40-6159-4a95-a027-69e155455e86",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "formatString": "General Date",
            "lineageTag": "280e2cad-d13d-4f7e-b487-8f7259f0246d",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "formatString": "0",
            "lineageTag": "40b0ce82-09ff-4219-8b42-1c1fac6bdde5",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "formatString": "0",
            "lineageTag": "c212a99a-7194-4339-bded-a5d0a971e4a8",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "10010957-3ded-4ddb-afc2-c8cf0c1092f8",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "lineageTag": "dd04b10d-0243-4ead-8b95-cfc414889add",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "25424e33-c2cd-47d0-a2e5-febb65951241",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "formatString": "0",
            "lineageTag": "fa2fa95a-193a-4fff-961b-9f54830da66f",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_1177f4db-4251-4842-aa66-5a04eafae0ce",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Date'[DateDate])), 1, 1), Date(Year(MAX('Date'[DateDate])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "799f7905-f2cf-45ca-99f4-7228ddf60a19",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "5515e42d-4a2e-4419-9516-8eb4b54b7b12"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "0bfeb59e-1422-4777-9991-9dbd8c2ddd85"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "61f7d72a-4bf0-428a-9a63-977e2b277300"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "3480551b-0d8e-45fa-a46c-2550c4f4a6d0"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "Branch",
        "lineageTag": "f0c6129d-6143-40bf-b729-693491295216",
        "columns": [
          {
            "name": "BranchId",
            "dataType": "int64",
            "sourceColumn": "BranchId",
            "formatString": "0",
            "lineageTag": "b656b0ce-1804-4768-9a3f-3d7c7966569f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "BranchCode",
            "dataType": "string",
            "sourceColumn": "BranchCode",
            "lineageTag": "3d2df4f1-b764-40c4-b4b0-c175ac5a6dac",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "BranchName",
            "dataType": "string",
            "sourceColumn": "BranchName",
            "lineageTag": "8f24de71-e78b-49cd-8d88-f26e86cc1139",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "BranchDeleted",
            "dataType": "boolean",
            "sourceColumn": "BranchDeleted",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "d1737398-a24a-40f0-aea0-15f4051d6908",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Branch",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"BORGERS.LOCAL\", \"JIP_DWH\"),",
                "    dbo_DimBranch = Source{[Schema=\"dbo\",Item=\"v_DimBranch\"]}[Data]",
                "in",
                "    dbo_DimBranch"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "Document",
        "lineageTag": "bfe0cede-d0f7-46e1-9ab3-33939fe58cc9",
        "columns": [
          {
            "name": "DocumentId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DocumentId",
            "formatString": "0",
            "lineageTag": "2c54eba6-fcf9-4cd5-bdfd-1efc56853888",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DocumentNumber",
            "dataType": "string",
            "sourceColumn": "DocumentNumber",
            "lineageTag": "a0dd1ac0-a11f-480c-a5f7-3f2a80934526",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Document",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"BORGERS.LOCAL\", \"JIP_DWH\"),",
                "    dbo_DimDocument = Source{[Schema=\"dbo\",Item=\"v_DimDocument\"]}[Data]",
                "in",
                "    dbo_DimDocument"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Document Count",
            "expression": "COUNTROWS()",
            "formatString": "0",
            "lineageTag": "cbe5c9a5-dc04-40f1-9788-bb0d777e2d71"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "Supplier",
        "lineageTag": "c4ac5f4e-ac57-40d0-abb6-a83a2bee7a94",
        "columns": [
          {
            "name": "SupplierId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SupplierId",
            "formatString": "0",
            "lineageTag": "3c11c621-01a6-4914-8fdf-b1f3b1eba9e3",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SupplierICO",
            "dataType": "string",
            "sourceColumn": "SupplierICO",
            "lineageTag": "0b8d7768-5f61-45fe-abba-6303fbe1f063",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Supplier Is JIP",
            "dataType": "boolean",
            "sourceColumn": "Supplier Is JIP",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "1b8a9b09-c04e-4bc2-bf98-1546f0da1999",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Supplier Is JIP CZ",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "IF(Supplier[Supplier Is JIP], \"Ano\", \"Ne\")",
            "lineageTag": "7b68d1c4-39cb-4fcd-b6a2-d2f8f050cd1c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SupplierName",
            "dataType": "string",
            "sourceColumn": "SupplierName",
            "lineageTag": "4aa73f18-af4f-4537-a0c6-70928520cb4d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SupplierCity",
            "dataType": "string",
            "sourceColumn": "SupplierCity",
            "lineageTag": "acca645c-bb8f-4c55-a430-92519897fc86",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SupplierFullName",
            "dataType": "string",
            "sourceColumn": "SupplierFullName",
            "lineageTag": "3119b480-6cb4-45bd-8875-7e657958fcce",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Supplier",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"BORGERS.LOCAL\", \"JIP_DWH\"),",
                "    dbo_DimSupplier = Source{[Schema=\"dbo\",Item=\"v_DimSupplier\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(dbo_DimSupplier,{{\"SupplierIsJIP\", \"Supplier Is JIP\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "Product",
        "lineageTag": "282f76cb-9194-485e-b4c2-ea58c0a18158",
        "columns": [
          {
            "name": "ProductId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductId",
            "formatString": "0",
            "lineageTag": "bb0e66a8-0676-4517-8cb7-eeff5b371276",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductCode",
            "dataType": "string",
            "sourceColumn": "ProductCode",
            "lineageTag": "375c1e39-c60e-4559-86a4-c0f47ba70dbe",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductName",
            "dataType": "string",
            "sourceColumn": "ProductName",
            "lineageTag": "de2411e8-7d55-4bb7-ba3f-45dcda8448b1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductFullName",
            "dataType": "string",
            "sourceColumn": "ProductFullName",
            "lineageTag": "b71d0ed0-5dc8-4a08-b27d-4ab59abd0d81",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductCardType",
            "dataType": "string",
            "sourceColumn": "ProductCardType",
            "lineageTag": "5f987e9c-617c-4cd8-88f7-9f1e15971186",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductSupplier",
            "dataType": "string",
            "sourceColumn": "ProductSupplier",
            "lineageTag": "fc578890-fe4e-439c-a6c2-9efe4835ce42",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductSupplierDescription",
            "dataType": "string",
            "sourceColumn": "ProductSupplierDescription",
            "lineageTag": "d228a223-b610-46c6-a35e-162788555cbc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductSupplierFullName",
            "dataType": "string",
            "sourceColumn": "ProductSupplierFullName",
            "lineageTag": "b89f223f-5a08-4291-99e2-c558ef861c67",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Product",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"BORGERS.LOCAL\", \"JIP_DWH\"),",
                "    dbo_DimProduct = Source{[Schema=\"dbo\",Item=\"v_DimProduct\"]}[Data]",
                "in",
                "    dbo_DimProduct"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "Fact Material Movement",
        "lineageTag": "eb949167-dcbd-47a6-bebd-6aa2de690348",
        "columns": [
          {
            "name": "MaterialMovement_DateId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MaterialMovement_DateId",
            "formatString": "0",
            "lineageTag": "ca0cca8c-bd76-4722-aa48-9851004a5a61",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MaterialMovement_BranchId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MaterialMovement_BranchId",
            "formatString": "0",
            "lineageTag": "94e014a7-83d4-4f28-b163-e8021f4bb201",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MaterialMovement_DocumentId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MaterialMovement_DocumentId",
            "formatString": "0",
            "lineageTag": "008e1d1a-8298-4f05-911b-ce4cd98e0867",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MaterialMovement_ProductId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MaterialMovement_ProductId",
            "formatString": "0",
            "lineageTag": "1209ac3f-2e04-4081-a046-6ad8dda295a2",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MaterialMovement_SupplierId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MaterialMovement_SupplierId",
            "formatString": "0",
            "lineageTag": "2499cd1d-77ed-43fb-bc56-0c28fe3bce56",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MaterialMovementTurnoverUnits",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "MaterialMovementTurnoverUnits",
            "lineageTag": "939747b7-7e67-417d-b657-6c6feedf055b",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "MaterialMovementTurnoverPalletes",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "MaterialMovementTurnoverPalletes",
            "lineageTag": "8618dd3e-7b1a-43d4-a54d-4d59b177ecff",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "MaterialMovement_MovementTypeId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MaterialMovement_MovementTypeId",
            "formatString": "0",
            "lineageTag": "6f64d5a7-2adb-4ccb-9bd5-dfd0fca2cddc",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MaterialMovementTurnoverFullPalletes",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MaterialMovementTurnoverFullPalletes",
            "formatString": "0",
            "lineageTag": "54b8a22d-a7ae-4dc5-af78-fe4fef6ea05e",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Fact Material Movement",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"BORGERS.LOCAL\", \"JIP_DWH\"),",
                "    dbo_FactMaterialMovement = Source{[Schema=\"dbo\",Item=\"v_FactMaterialMovement\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(dbo_FactMaterialMovement,{{\"MaterialMovementTurnoverPalletes\", \"MaterialMovementTurnoverPalletes\"}, {\"MaterialMovementTurnoverUoM\", \"MaterialMovementTurnoverUnits\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Material Movement Turnover Count",
            "expression": "COUNTROWS()",
            "formatString": "#,0",
            "lineageTag": "9049d144-1fda-424c-8c54-7a014797b139"
          },
          {
            "name": "Material Movement Internal Count",
            "expression": [
              "CALCULATE(",
              "    COUNTROWS(),",
              "    Supplier[Supplier Is JIP]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "fdf22aec-26b8-4a7e-8640-ba91029fb5a9"
          },
          {
            "name": "Material Movement External Count",
            "expression": [
              "CALCULATE(",
              "    COUNTROWS(),",
              "    NOT( Supplier[Supplier Is JIP])",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "de617168-c517-406a-8465-423c4632d1b9"
          },
          {
            "name": "Material Movement External Palletes",
            "expression": [
              "CALCULATE(",
              "    SUM('Fact Material Movement'[MaterialMovementTurnoverPalletes]),",
              "    NOT( Supplier[Supplier Is JIP])",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "75d83dd6-1f28-490f-abd6-6119214229a6"
          },
          {
            "name": "Material Movement Internall Palletes",
            "expression": [
              "CALCULATE(",
              "    SUM('Fact Material Movement'[MaterialMovementTurnoverPalletes]),",
              "     Supplier[Supplier Is JIP]",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "lineageTag": "2ebe5ba5-2f0e-4a8b-b992-b2d320fd516b"
          },
          {
            "name": "Material Movement External Palletes %",
            "expression": "[Material Movement External Palletes] / SUM([MaterialMovementTurnoverPalletes])",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "785bd327-0429-4f92-b68c-0d2d6fc9f529"
          },
          {
            "name": "Material Movement Document Count",
            "expression": "DISTINCTCOUNT('Fact Material Movement'[MaterialMovement_DocumentId])",
            "formatString": "0",
            "lineageTag": "53c2819a-14d2-44cd-b4e2-c29b29b8b013"
          },
          {
            "name": "Material Movement Turnover Palletes",
            "expression": "SUM('Fact Material Movement'[MaterialMovementTurnoverPalletes])",
            "lineageTag": "4b2bd784-4438-4fec-8682-2b643fa746d0",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Material Movement Turnover Units",
            "expression": "SUM('Fact Material Movement'[MaterialMovementTurnoverUnits])",
            "lineageTag": "051d5dea-4370-4a5f-bccb-c8a578d7887d",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Material Movement Day Count",
            "expression": "DISTINCTCOUNT('Fact Material Movement'[MaterialMovement_DateId])",
            "formatString": "0",
            "lineageTag": "453fc21c-50da-4553-9665-736da836451c"
          },
          {
            "name": "Material Movement Product Count",
            "expression": "DISTINCTCOUNT('Fact Material Movement'[MaterialMovement_ProductId])",
            "formatString": "0",
            "lineageTag": "29896474-33dd-4319-a225-bba382704edc"
          },
          {
            "name": "Material Movement Turnover Full Palletes",
            "expression": "SUM('Fact Material Movement'[MaterialMovementTurnoverFullPalletes])",
            "formatString": "#,0",
            "lineageTag": "398ee66c-5e8e-4ef6-ac65-099b64d82fb2"
          },
          {
            "name": "Material Movement Supplier Count",
            "expression": "DISTINCTCOUNT('Fact Material Movement'[MaterialMovement_SupplierId])",
            "formatString": "0",
            "lineageTag": "3580e7dc-0630-4b15-b0bd-d4c7b059f07e"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "ABC",
        "lineageTag": "6a84c040-84ee-4de6-9104-38455827ad12",
        "columns": [
          {
            "name": "ABCId",
            "dataType": "int64",
            "sourceColumn": "ABCId",
            "formatString": "0",
            "lineageTag": "c07b97ab-c19b-4eb7-baeb-9dc0612f33a4",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ABCName",
            "dataType": "string",
            "sourceColumn": "ABCName",
            "lineageTag": "d4f3b3fc-3826-4d26-ac10-dc3ca372a200",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ABCFrom",
            "dataType": "double",
            "sourceColumn": "ABCFrom",
            "lineageTag": "52c8a020-1e2c-416a-987b-923e8e79f0a5",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ABCTo",
            "dataType": "double",
            "sourceColumn": "ABCTo",
            "lineageTag": "99bb5ce1-b5a1-4dcd-a289-c50237321ca0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "ABC",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"BORGERS.LOCAL\", \"JIP_DWH\"),",
                "    adm_ABC = Source{[Schema=\"adm\",Item=\"ABC\"]}[Data]",
                "in",
                "    adm_ABC"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Orderline",
            "expression": [
              "",
              "VAR SalesByProduct =",
              "    CALCULATETABLE (",
              "        ADDCOLUMNS (",
              "            SUMMARIZE ( 'Fact Material Movement', 'Fact Material Movement'[MaterialMovement_ProductId] ),",
              "            \"@ProdSales\", [Material Movement Turnover Count]",
              "        ),",
              "        ALLSELECTED ( 'Fact Material Movement' )",
              "    )",
              "VAR AllSales =",
              "    CALCULATE (",
              "        [Material Movement Turnover Count],",
              "        ALLSELECTED ( 'Fact Material Movement' )",
              "    )",
              "VAR CumulatedPctByProduct =",
              "    ADDCOLUMNS (",
              "        SalesByProduct,",
              "        \"@CumulatedPct\",",
              "        VAR CurrentSalesAmt = [@ProdSales]",
              "        VAR CumulatedSales =",
              "            FILTER (",
              "                SalesByProduct,",
              "                [@ProdSales] >= CurrentSalesAmt",
              "            )",
              "        VAR CumulatedSalesAmount =",
              "            SUMX (",
              "                CumulatedSales,",
              "                [@ProdSales]",
              "            )",
              "        VAR Perc =",
              "            DIVIDE (",
              "                CumulatedSalesAmount,",
              "                AllSales",
              "            )",
              "        RETURN",
              "            Perc",
              "    )",
              "VAR ProductsInClass =",
              "    FILTER (",
              "        CROSSJOIN (",
              "            CumulatedPctByProduct,",
              "            'ABC'",
              "        ),",
              "        AND (",
              "            [@CumulatedPct] > 'ABC'[ABCFrom],",
              "            [@CumulatedPct] <= 'ABC'[ABCTo]",
              "        )",
              "    )",
              "VAR Result =",
              "    CALCULATE (             -- The pattern is the same for every measure, just",
              "        [Material Movement Turnover Count],     -- change this measure reference for other measures",
              "        KEEPFILTERS ( ProductsInClass )",
              "    )",
              "RETURN",
              "    Result"
            ],
            "formatString": "#,0",
            "lineageTag": "4db7f335-8cad-4590-b8fe-fba6c6542be1"
          },
          {
            "name": "Products",
            "expression": [
              "",
              "VAR SalesByProduct =",
              "    CALCULATETABLE (",
              "        ADDCOLUMNS (",
              "            SUMMARIZE ( 'Fact Material Movement', 'Fact Material Movement'[MaterialMovement_ProductId] ),",
              "            \"@ProdSales\", [Material Movement Turnover Count]",
              "        ),",
              "        ALLSELECTED ( 'Fact Material Movement' )",
              "    )",
              "VAR AllSales =",
              "    CALCULATE (",
              "        [Material Movement Turnover Count],",
              "        ALLSELECTED ( 'Fact Material Movement' )",
              "    )",
              "VAR CumulatedPctByProduct =",
              "    ADDCOLUMNS (",
              "        SalesByProduct,",
              "        \"@CumulatedPct\",",
              "        VAR CurrentSalesAmt = [@ProdSales]",
              "        VAR CumulatedSales =",
              "            FILTER (",
              "                SalesByProduct,",
              "                [@ProdSales] >= CurrentSalesAmt",
              "            )",
              "        VAR CumulatedSalesAmount =",
              "            SUMX (",
              "                CumulatedSales,",
              "                [@ProdSales]",
              "            )",
              "        VAR Perc =",
              "            DIVIDE (",
              "                CumulatedSalesAmount,",
              "                AllSales",
              "            )",
              "        RETURN",
              "            Perc",
              "    )",
              "VAR ProductsInClass =",
              "    FILTER (",
              "        CROSSJOIN (",
              "            CumulatedPctByProduct,",
              "            'ABC'",
              "        ),",
              "        AND (",
              "            [@CumulatedPct] > 'ABC'[ABCFrom],",
              "            [@CumulatedPct] <= 'ABC'[ABCTo]",
              "        )",
              "    )",
              "VAR Result =",
              "    CALCULATE (             -- The pattern is the same for every measure, just",
              "        [Material Movement Product Count],     -- change this measure reference for other measures",
              "        KEEPFILTERS ( ProductsInClass )",
              "    )",
              "RETURN",
              "    Result"
            ],
            "formatString": "#,0",
            "lineageTag": "0fe777db-64bf-4bf4-a690-ccd363bc5fd5"
          },
          {
            "name": "Units",
            "expression": [
              "",
              "VAR SalesByProduct =",
              "    CALCULATETABLE (",
              "        ADDCOLUMNS (",
              "            SUMMARIZE ( 'Fact Material Movement', 'Fact Material Movement'[MaterialMovement_ProductId] ),",
              "            \"@ProdSales\", [Material Movement Turnover Count]",
              "        ),",
              "        ALLSELECTED ( 'Fact Material Movement' )",
              "    )",
              "VAR AllSales =",
              "    CALCULATE (",
              "        [Material Movement Turnover Count],",
              "        ALLSELECTED ( 'Fact Material Movement' )",
              "    )",
              "VAR CumulatedPctByProduct =",
              "    ADDCOLUMNS (",
              "        SalesByProduct,",
              "        \"@CumulatedPct\",",
              "        VAR CurrentSalesAmt = [@ProdSales]",
              "        VAR CumulatedSales =",
              "            FILTER (",
              "                SalesByProduct,",
              "                [@ProdSales] >= CurrentSalesAmt",
              "            )",
              "        VAR CumulatedSalesAmount =",
              "            SUMX (",
              "                CumulatedSales,",
              "                [@ProdSales]",
              "            )",
              "        VAR Perc =",
              "            DIVIDE (",
              "                CumulatedSalesAmount,",
              "                AllSales",
              "            )",
              "        RETURN",
              "            Perc",
              "    )",
              "VAR ProductsInClass =",
              "    FILTER (",
              "        CROSSJOIN (",
              "            CumulatedPctByProduct,",
              "            'ABC'",
              "        ),",
              "        AND (",
              "            [@CumulatedPct] > 'ABC'[ABCFrom],",
              "            [@CumulatedPct] <= 'ABC'[ABCTo]",
              "        )",
              "    )",
              "VAR Result =",
              "    CALCULATE (             -- The pattern is the same for every measure, just",
              "        [Material Movement Turnover Units],     -- change this measure reference for other measures",
              "        KEEPFILTERS ( ProductsInClass )",
              "    )",
              "RETURN",
              "    Result"
            ],
            "formatString": "#,0",
            "lineageTag": "b1c3abfa-c4ee-44c5-83c5-daf9098d0b18"
          },
          {
            "name": "ICO Palletes",
            "expression": [
              "",
              "VAR SalesByProduct =",
              "    CALCULATETABLE (",
              "        ADDCOLUMNS (",
              "            SUMMARIZE ( 'Fact Material Movement', 'Fact Material Movement'[MaterialMovement_SupplierId] ),",
              "            \"@ProdSales\", [Material Movement Turnover Palletes]",
              "        ),",
              "        ALLSELECTED ( 'Fact Material Movement' )",
              "    )",
              "VAR AllSales =",
              "    CALCULATE (",
              "        [Material Movement Turnover Palletes],",
              "        ALLSELECTED ( 'Fact Material Movement' )",
              "    )",
              "VAR CumulatedPctByProduct =",
              "    ADDCOLUMNS (",
              "        SalesByProduct,",
              "        \"@CumulatedPct\",",
              "        VAR CurrentSalesAmt = [@ProdSales]",
              "        VAR CumulatedSales =",
              "            FILTER (",
              "                SalesByProduct,",
              "                [@ProdSales] >= CurrentSalesAmt",
              "            )",
              "        VAR CumulatedSalesAmount =",
              "            SUMX (",
              "                CumulatedSales,",
              "                [@ProdSales]",
              "            )",
              "        VAR Perc =",
              "            DIVIDE (",
              "                CumulatedSalesAmount,",
              "                AllSales",
              "            )",
              "        RETURN",
              "            Perc",
              "    )",
              "VAR ProductsInClass =",
              "    FILTER (",
              "        CROSSJOIN (",
              "            CumulatedPctByProduct,",
              "            'ABC'",
              "        ),",
              "        AND (",
              "            [@CumulatedPct] > 'ABC'[ABCFrom],",
              "            [@CumulatedPct] <= 'ABC'[ABCTo]",
              "        )",
              "    )",
              "VAR Result =",
              "    CALCULATE (             -- The pattern is the same for every measure, just",
              "        [Material Movement Supplier Count],     -- change this measure reference for other measures",
              "        KEEPFILTERS ( ProductsInClass )",
              "    )",
              "RETURN",
              "    Result"
            ],
            "lineageTag": "fe540614-8d4e-4d71-97f9-6deab2c45ab9"
          },
          {
            "name": "ICO Units",
            "expression": [
              "",
              "VAR SalesByProduct =",
              "    CALCULATETABLE (",
              "        ADDCOLUMNS (",
              "            SUMMARIZE ( 'Fact Material Movement', 'Fact Material Movement'[MaterialMovement_SupplierId] ),",
              "            \"@ProdSales\", [Material Movement Turnover Units]",
              "        ),",
              "        ALLSELECTED ( 'Fact Material Movement' )",
              "    )",
              "VAR AllSales =",
              "    CALCULATE (",
              "        [Material Movement Turnover Units],",
              "        ALLSELECTED ( 'Fact Material Movement' )",
              "    )",
              "VAR CumulatedPctByProduct =",
              "    ADDCOLUMNS (",
              "        SalesByProduct,",
              "        \"@CumulatedPct\",",
              "        VAR CurrentSalesAmt = [@ProdSales]",
              "        VAR CumulatedSales =",
              "            FILTER (",
              "                SalesByProduct,",
              "                [@ProdSales] >= CurrentSalesAmt",
              "            )",
              "        VAR CumulatedSalesAmount =",
              "            SUMX (",
              "                CumulatedSales,",
              "                [@ProdSales]",
              "            )",
              "        VAR Perc =",
              "            DIVIDE (",
              "                CumulatedSalesAmount,",
              "                AllSales",
              "            )",
              "        RETURN",
              "            Perc",
              "    )",
              "VAR ProductsInClass =",
              "    FILTER (",
              "        CROSSJOIN (",
              "            CumulatedPctByProduct,",
              "            'ABC'",
              "        ),",
              "        AND (",
              "            [@CumulatedPct] > 'ABC'[ABCFrom],",
              "            [@CumulatedPct] <= 'ABC'[ABCTo]",
              "        )",
              "    )",
              "VAR Result =",
              "    CALCULATE (             -- The pattern is the same for every measure, just",
              "        [Material Movement Supplier Count],     -- change this measure reference for other measures",
              "        KEEPFILTERS ( ProductsInClass )",
              "    )",
              "RETURN",
              "    Result"
            ],
            "formatString": "0",
            "lineageTag": "808e03e4-52f7-46db-b099-34673c842787"
          },
          {
            "name": "ICO Orderline",
            "expression": [
              "",
              "VAR SalesByProduct =",
              "    CALCULATETABLE (",
              "        ADDCOLUMNS (",
              "            SUMMARIZE ( 'Fact Material Movement', 'Fact Material Movement'[MaterialMovement_SupplierId] ),",
              "            \"@ProdSales\", [Material Movement Turnover Count]",
              "        ),",
              "        ALLSELECTED ( 'Fact Material Movement' )",
              "    )",
              "VAR AllSales =",
              "    CALCULATE (",
              "        [Material Movement Turnover Count],",
              "        ALLSELECTED ( 'Fact Material Movement' )",
              "    )",
              "VAR CumulatedPctByProduct =",
              "    ADDCOLUMNS (",
              "        SalesByProduct,",
              "        \"@CumulatedPct\",",
              "        VAR CurrentSalesAmt = [@ProdSales]",
              "        VAR CumulatedSales =",
              "            FILTER (",
              "                SalesByProduct,",
              "                [@ProdSales] >= CurrentSalesAmt",
              "            )",
              "        VAR CumulatedSalesAmount =",
              "            SUMX (",
              "                CumulatedSales,",
              "                [@ProdSales]",
              "            )",
              "        VAR Perc =",
              "            DIVIDE (",
              "                CumulatedSalesAmount,",
              "                AllSales",
              "            )",
              "        RETURN",
              "            Perc",
              "    )",
              "VAR ProductsInClass =",
              "    FILTER (",
              "        CROSSJOIN (",
              "            CumulatedPctByProduct,",
              "            'ABC'",
              "        ),",
              "        AND (",
              "            [@CumulatedPct] > 'ABC'[ABCFrom],",
              "            [@CumulatedPct] <= 'ABC'[ABCTo]",
              "        )",
              "    )",
              "VAR Result =",
              "    CALCULATE (             -- The pattern is the same for every measure, just",
              "        [Material Movement Supplier Count],     -- change this measure reference for other measures",
              "        KEEPFILTERS ( ProductsInClass )",
              "    )",
              "RETURN",
              "    Result"
            ],
            "formatString": "0",
            "lineageTag": "07e975ef-1245-4690-993b-ca0f814ae44e"
          }
        ]
      },
      {
        "name": "Measure Selection",
        "lineageTag": "33932f60-2e03-4887-98bd-b5d74de633ab",
        "columns": [
          {
            "name": "MeasureSelectionId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MeasureSelectionId",
            "formatString": "0",
            "lineageTag": "93e38c07-0f0e-42e6-aff2-833f0007e7e0",
            "summarizeBy": "count",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MeasureSelectionName",
            "dataType": "string",
            "sourceColumn": "MeasureSelectionName",
            "lineageTag": "791aaaeb-290f-4cea-ad8c-4f413738b9b2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MeasureSelectionIndex",
            "dataType": "int64",
            "sourceColumn": "MeasureSelectionIndex",
            "formatString": "0",
            "lineageTag": "cf5ccae0-b457-4791-8556-737748b840df",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Measure Selection",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"BORGERS.LOCAL\", \"JIP_DWH\"),",
                "    adm_MeasureSelection = Source{[Schema=\"adm\",Item=\"MeasureSelection\"]}[Data]",
                "in",
                "    adm_MeasureSelection"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Selekce",
            "expression": [
              "",
              "SWITCH( TRUE(),",
              "\tSELECTEDVALUE( 'Measure Selection'[MeasureSelectionName] ) = \"# Orderlines\", [Material Movement Turnover Count],",
              "\tSELECTEDVALUE( 'Measure Selection'[MeasureSelectionName] ) = \"# MJ\", [Material Movement Turnover Units] ,",
              "    SELECTEDVALUE( 'Measure Selection'[MeasureSelectionName] ) = \"# Objednvky\", [Material Movement Document Count],",
              "    SELECTEDVALUE( 'Measure Selection'[MeasureSelectionName] ) = \"# Palety\", [Material Movement Turnover Palletes],",
              "[Material Movement Turnover Count])"
            ],
            "formatString": "#,0",
            "lineageTag": "ffb40f9b-837b-42cb-8cf6-3fa0e1ec8fd6"
          },
          {
            "name": " za den",
            "expression": "[Selekce] / 'Fact Material Movement'[Material Movement Day Count]",
            "lineageTag": "c38853e4-9084-4e7d-a92c-9d4c770d9346",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "90 % perc",
            "expression": [
              "",
              "CALCULATE (",
              "    PERCENTILEX.INC (",
              "        VALUES ( 'Fact Material Movement'[MaterialMovement_DateId] ),",
              "        [Selekce],",
              "        0.9",
              "    ),",
              "    ALLSELECTED ( 'Date'[DateDate] )",
              ")",
              ""
            ],
            "lineageTag": "a54aca8b-66e4-4fc9-ac76-ae4a48f27b0a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "peak factor",
            "expression": "divide ( [90 % perc] , [ za den], 0 )",
            "lineageTag": "12603aff-f171-438a-b75e-ff38260fab0e",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": " za den ve",
            "expression": [
              "",
              "CALCULATE (",
              "    AVERAGEX ( VALUES ( 'Fact Material Movement'[MaterialMovement_DateId] ), [Selekce] ),",
              "    ALLSELECTED( ( 'Date'[DateDate] )",
              "))"
            ],
            "lineageTag": "9353bc7f-d804-4242-bb06-97f992d55687",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ]
      },
      {
        "name": "Movement Type",
        "lineageTag": "cc0d9caf-80e6-44ba-923b-d58e76849b42",
        "columns": [
          {
            "name": "MovementTypeId",
            "dataType": "int64",
            "sourceColumn": "MovementTypeId",
            "formatString": "0",
            "lineageTag": "794ffc21-76bc-40e2-91ee-3a360170e446",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MovementTypeName",
            "dataType": "string",
            "sourceColumn": "MovementTypeName",
            "lineageTag": "f4220650-c0a9-4a1a-a823-65724eb9136f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Movement Type",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"BORGERS.LOCAL\", \"JIP_DWH\"),",
                "    dbo_v_DimMovementType = Source{[Schema=\"dbo\",Item=\"v_DimMovementType\"]}[Data]",
                "in",
                "    dbo_v_DimMovementType"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "3eba4621-8df7-41e7-87e9-93150d8259a1",
        "fromTable": "Date",
        "fromColumn": "DateDate",
        "toTable": "LocalDateTable_1177f4db-4251-4842-aa66-5a04eafae0ce",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "003c3516-e045-7dd7-fb38-cad81b8459ca",
        "fromTable": "Fact Material Movement",
        "fromColumn": "MaterialMovement_BranchId",
        "toTable": "Branch",
        "toColumn": "BranchId"
      },
      {
        "name": "ce999be4-daba-3e79-27b9-2c9648ba8de5",
        "fromTable": "Fact Material Movement",
        "fromColumn": "MaterialMovement_DateId",
        "toTable": "Date",
        "toColumn": "DateId"
      },
      {
        "name": "13678c1a-e37f-7640-e822-249c4d77e811",
        "fromTable": "Fact Material Movement",
        "fromColumn": "MaterialMovement_ProductId",
        "toTable": "Product",
        "toColumn": "ProductId"
      },
      {
        "name": "7173972e-8bb7-214a-c6d2-08896b912b29",
        "fromTable": "Fact Material Movement",
        "fromColumn": "MaterialMovement_DocumentId",
        "toTable": "Document",
        "toColumn": "DocumentId"
      },
      {
        "name": "d64d1f94-7163-15c1-dca4-f2feff9822fe",
        "fromTable": "Fact Material Movement",
        "fromColumn": "MaterialMovement_SupplierId",
        "toTable": "Supplier",
        "toColumn": "SupplierId"
      },
      {
        "name": "0d94c27f-639a-3886-0848-4cf3dc6148b1",
        "fromTable": "Fact Material Movement",
        "fromColumn": "MaterialMovement_MovementTypeId",
        "toTable": "Movement Type",
        "toColumn": "MovementTypeId"
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Date\",\"Branch\",\"Document\",\"Supplier\",\"Product\",\"Fact Material Movement\",\"ABC\",\"Measure Selection\",\"Movement Type\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"SortArrays\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Shared Expressions\",\"Perspectives\",\"Relationships\",\"Roles\",\"Tables\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Tables/Calculation Items\",\"Translations\"]}"
      }
    ]
  }
}