CREATE VIEW [dbo].[v_DimProduct]
AS
SELECT [ProductId]
	,[ProductCode]
	,[ProductName]
	,[dbo].[f_GetFullName]([ProductCode], [ProductName]) AS [ProductFullName]
	,[ProductCardType]
	,[ProductSupplier]
	,[ProductSupplierDescription]
	,[dbo].[f_GetFullName]([ProductSupplier], [ProductSupplierDescription]) AS [ProductSupplierFullName]
FROM [DimProduct]
