CREATE VIEW [dbo].[v_FactMaterialMovement]
AS
SELECT 1 AS [MaterialMovement_MovementTypeId]
	,[MaterialMovement_DateId]
	,[MaterialMovement_BranchId]
	,[MaterialMovement_DocumentId]
	,[MaterialMovement_ProductId]
	,[MaterialMovement_SupplierId]
	,[MaterialMovementTurnoverUoM]
	,[MaterialMovementTurnoverPalletes]
	,CONVERT(int, [MaterialMovementTurnoverPalletes]) AS [MaterialMovementTurnoverFullPalletes]
FROM [FactMaterialMovement]
INNER JOIN [v_BrancFilter] ON [MaterialMovement_BranchId] = [BranchId]

UNION ALL

SELECT 2 AS [MaterialMovement_MovementTypeId]
	,[MaterialSale_DateId]
	,[MaterialSale_BranchId]
	,[MaterialSale_DocumentId]
	,[MaterialSale_ProductId]
	,[MaterialSale_SupplierId]
	,[MaterialSaleTurnoverUoM]
	,[MaterialSaleTurnoverPalletes]
	,CONVERT(int, [MaterialSaleTurnoverPalletes]) AS [MaterialSaleTurnoverFullPalletes]
FROM [dbo].[FactMaterialSale]
INNER JOIN [v_BrancFilter] ON [MaterialSale_BranchId] = [BranchId]
