CREATE TABLE [adm].[ETLLog]
(
	[ETLLogId] INT NOT NULL  IDENTITY (1,1) CONSTRAINT [PK_adm_ETLLog] PRIMARY KEY CLUSTERED,
	[ETLLogServerExecutionId] BIGINT NOT NULL,
	[ETLLog_ETLEventId] INT NOT NULL CONSTRAINT [FK_adm_ETLLog_ETLLog_ETLEventId] FOREIGN KEY REFERENCES [adm].[ETLEvent] ([ETLEventId]),
	[ETLLogStart] DATETIME NOT NULL,
	[ETLLogFinish] DATETIME NULL,
	[ETLLogPackageName] sysname NOT NULL,
	[ETLLogErrorCode] INT NULL,
	[ETLLogErrorMessage] NVARCHAR(MAX) NULL,
	[ETLLogLogin] NVARCHAR(128) NULL
)
